name: LitmusDocs-CI
on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "website/**"

jobs:
  embedmdCheck_and_linksVerification:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{steps.getcommit.outputs.sha}}

      - uses: actions/setup-go@v2
        with:
          stable: "false"
          go-version: "1.14.0"

      - name: Links Verification
        run: |
          go get -u -v github.com/bmuschko/link-verifier
          link-verifier --dirs website,README.md --fail=false

      - name: Installing and Running embedmed
        run: |
          sudo apt install boxes
          go get github.com/campoy/embedmd
          cd website/docs
          embedmd -w $(find *.md)
        continue-on-error: true

      - name: embedmd check
        run: |
          export TERM=xterm-256color
          count=$(git status -s| wc -l)
          if [ "$count" -ne "0" ]
          then
            tput setaf 1; echo "Error: embedmd check failed"
            tput setaf 4; echo "Please check the following files need an embedmd run:"
            output=$(git status -s)
            echo "$output" | boxes -d stone -p a2v1
            tput setaf 3; echo "Please follow the instructions to run embedmd:"
            tput setaf 3; echo "cd website/docs"
            tput setaf 3; echo "embedmd -w \$(find *.md)"
            tput setaf 6; echo "For more info visit https://github.com/litmuschaos/litmus-docs/blob/master/CONTRIBUTING.md"
            exit 1
          else
            tput setaf 2; echo "Nothing to embed"
          fi
        shell: sh

  ci:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: docker build -t $GITHUB_REPOSITORY .

  Spellcheck:
    runs-on: ubuntu-latest
    steps:
      # The checkout step
      - uses: actions/checkout@master
      - uses: rojopolis/spellcheck-github-actions@0.11.0
        name: Spellcheck
        with:
          source_files: "website/docs/*.md"
          task_name: Markdown

  NetlifyPreview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      # Run npm install and build on our code
      - run: |
          cd website
          npm install
          npm run build
      # Deploy to Netlify-Preview
      - uses: netlify/actions/cli@master
        id: preview
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=website/build
          secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'

      - name: Check if bot already commented or not
        uses: peter-evans/find-comment@v1
        id: previewComment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: "github-actions[bot]"
          body-includes: "Netlify-Preview Details :"

      - name: Comments the links for preview if build passed successfully
        if: ${{ success() }}
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ steps.previewComment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            **Netlify-Preview Details :**

            **ðŸš€ Preview Link** - ${{ steps.preview.outputs.NETLIFY_URL }}
            **ðŸ’» Netlify Logs Link** - ${{ steps.preview.outputs.NETLIFY_LOGS_URL }}
          edit-mode: replace
          reactions: rocket, hooray
